// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNCFWwqC6rT2bD0U0BugowcCTArt5N4I',
    appId: '1:639190595200:web:092df5ad0b4084011b5865',
    messagingSenderId: '639190595200',
    projectId: 'authtest-5562c',
    authDomain: 'authtest-5562c.firebaseapp.com',
    storageBucket: 'authtest-5562c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiuGlM_3ukMBMjHw4UGwhhpRXPGlT2bw',
    appId: '1:639190595200:android:775fe873c754a2621b5865',
    messagingSenderId: '639190595200',
    projectId: 'authtest-5562c',
    storageBucket: 'authtest-5562c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Iy2z2rLUSNDpWMqD0mB3A_bZ5Xwi2TI',
    appId: '1:639190595200:ios:e5c1dd508b8791e31b5865',
    messagingSenderId: '639190595200',
    projectId: 'authtest-5562c',
    storageBucket: 'authtest-5562c.appspot.com',
    iosClientId: '639190595200-5cf8h6ppnq9bh2l5neb8dmqsn7l06jl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationFirebase',
  );
}
